# Generated by Django 2.2 on 2020-09-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-publish',)},
        ),
    ]
